### ISSUE TITLE
Regex Match Parser Errors without decimal point in Percent Identity 

### ISSUE THREAD

**Issue by kthurimella** [telatin/cdhit-parser#1]
I have used PSI CD Blast to do some low seq id clustering and sometimes it outputs a cluster member's PID as a whole percentage without a decimal:

e.g. 

```text
at 0.0/922aa/40%
```

and errors:

```
TypeError                                 Traceback (most recent call last)
/var/folders/c2/r71spmj97fj8fdlg4z8b87jh0000gp/T/ipykernel_90856/715681207.py in <module>
     19                 attrs = attrpatt.match(match["attr"])
     20                 print(match["attr"])
---> 21                 print(attrs["percent"])
     22 
     23         if line == ">Cluster 11\n":

TypeError: 'NoneType' object is not subscriptable`
```

Currently the attrpattern in the _parser() has a strict enforcement on a decimal point:
```python
attrpatt = re.compile(r'(?P<ref>\*|at) .*?(?P<strand>[+-]?)\/?(?P<percent>\d+\.\d+)%')
```
However, I think by making the requirement optional it will be able to hold all functionality and still catch cases like this:
```python
attrpatt = re.compile(r'(?P<ref>\*|at) .*?(?P<strand>[+-]?)\/?(?P<percent>\d+\.?\d+)%')
```
Would you be willing to change that in your functionality?

**Comment by kthurimella** [comment]
PR Here: https://github.com/telatin/cdhit-parser/pull/2

**Comment by telatin** [comment]
Hi, thanks for reporting and for the PR! Will check it, meanwhile would you be able to attach a minimal file that causes the problem? Thanks a million

**Comment by kthurimella** [comment]
Certainly, I've attached an example of a cluster here! Let me know if you need any other information.

[example.txt](https://github.com/telatin/cdhit-parser/files/10510733/example.txt)

**Comment by telatin** [comment]
Brilliant thanks, will try to have a look within 2 weeks!

**Comment by kthurimella** [comment]
Hello @telatin were you able to look at the bug and replicate it?

**Comment by telatin** [comment]
Thanks for your help @kthurimella !

**Comment by telatin** [comment]
to allow for 1 digit percentages like

```text
at 0.0/922aa/4%
```

I will make the digits after the dot optional like

```python
attrpatt = r"(?P<ref>\*|at) .*?(?P<strand>[+-]?)\/?(?P<percent>\d+\.?\d*)%"
```
